version: "3.9"

services:
  db:
    image: postgres:15
    container_name: notes-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notes-net

  backend:
    build: ./backend
    container_name: notes-backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:password@db:5432/notes_db
    ports:
      - "3001:3001"
    networks:
      - notes-net

  frontend:
    build: ./frontend
    container_name: notes-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://20.215.233.48:3001
    ports:
      - "3000:3000"
    networks:
      - notes-net

volumes:
  postgres_data:

networks:
  notes-net:
    driver: bridge
